# Generated by Django 5.2.1 on 2025-06-10 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription_plan', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('price', models.IntegerField(default=100, help_text='In cents')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
                ('greeting_message', models.CharField()),
            ],
        ),
    ]
