# Generated by Django 5.2.1 on 2025-06-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subscriptionplan_greeting_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriber_stripe_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
