# Generated by Django 5.2.1 on 2025-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_subscriber_stripe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_stripe_email',
            field=models.EmailField(blank=True, help_text='Email linked to stripe', max_length=254, null=True),
        ),
    ]
