version: "3.8"
services:
  db:
    image: postgres:17
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: postgres_db_dev 
  backend:
    build:
      context: ./backend 
    volumes:
      - ./backend:/django
    ports:
      - "8000:8000"
    image: blog_backend_dev
    container_name: blog_backend_dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db  
  frontend:
    build:
      context: ./frontend 
    volumes:
      - ./frontend:/react
      - /react/node_modules
    ports:
      - "3000:3000"
    image: blog_frontend_dev
    container_name: blog_frontend_dev
    command: npm run dev -- --host
    env_file:
      - .env
    