version: "3.8"
services:
  backend:
    build:
      context: ./backend 
    volumes:
      - ./backend:/django
    ports:
      - "8000:8000"
    image: blog_backend
    container_name: blog_backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
